### Get All Students
GET http://localhost:8080/academics/api/students
Accept: application/json

### Create A New Student
POST http://localhost:8080/academics/api/students
Content-Type: application/json

{
 "email": "joao@mail.com",
 "name": "Joao Vieira",
 "username": "dranzus",
 "password": "1234",
 "courseCode": 1
}

### Get All Courses
GET http://localhost:8080/academics/api/courses
Accept: application/json

### Create A New Course
POST http://localhost:8080/academics/api/courses
Content-Type: application/json

{
  "name": "Computer Science",
  "code": 4
}

### Get student details
GET http://localhost:8080/academics/api/students/dranzus
Accept: application/json

### Get student subjects
GET http://localhost:8080/academics/api/students/dranzus/subjects
Accept: application/json

### Update Student
PUT http://localhost:8080/academics/api/students/dranzus
Content-Type: application/json

{
  "email": "joao@mail.pt",
  "name": "Joao Vieira",
  "username": "dranzus",
  "password": "1234",
  "courseCode": 1
}