### Get All Students
GET http://localhost:8080/academics/api/students
Accept: application/json

### Create A New Student
POST http://localhost:8080/academics/api/students
Content-Type: application/json

{
 "email": "joao@mail.com",
 "name": "Joao Vieira",
 "username": "dranzus",
 "password": "1234",
 "courseCode": 1
}

### Get All Courses
GET http://localhost:8080/academics/api/courses
Accept: application/json

### Create A New Course
POST http://localhost:8080/academics/api/courses
Content-Type: application/json

{
  "name": "Computer Science",
  "code": 4
}

### Get student details
GET http://localhost:8080/academics/api/students/dranzus
Accept: application/json

### Get student subjects
GET http://localhost:8080/academics/api/students/dranzus/subjects
Accept: application/json

### Update Student
PUT http://localhost:8080/academics/api/students/dranzus
Content-Type: application/json

{
  "email": "joao@mail.pt",
  "name": "Joao Vieira",
  "username": "dranzus",
  "password": "1234",
  "courseCode": 1
}

### Send Email
POST http://localhost:8080/academics/api/students/dranzus/email
Content-Type: application/json

{
    "subject": "Test",
    "body": "Hello World"
}


### REQUEST JWT TOKEN
POST http://localhost:8080/academics/api/auth/login
Content-Type: application/json
Accept: application/json

{ "username": "admin", "password": "admin" }

### GET ALL STUDENTS
GET http://localhost:8080/academics/api/students
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczMjA1NDU3NCwiZXhwIjoxNzMyMDU4MTc0fQ.q1SwS2Y4pnke44eXqIkhDqzmDGjmGjh8D5czCxPUoBT9xpkXcPdi6sCIowKIql-E

### TEST AUTH ENDPOINTS
GET http://localhost:8080/academics/api/auth/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTczMjA1NDU3NCwiZXhwIjoxNzMyMDU4MTc0fQ.q1SwS2Y4pnke44eXqIkhDqzmDGjmGjh8D5czCxPUoBT9xpkXcPdi6sCIowKIql-E
